version: '3.8'

services:
  # Ollama service for running LLMs locally
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 12G  # Adjust based on your available RAM

  # Meeting Summarizer API
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - meeting_data:/app/job_results
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - WORKERS=1
      - LLM_PROVIDER=ollama
      - OLLAMA_API_BASE=http://ollama:11434
      - OLLAMA_MODEL=mistral
      - OLLAMA_SUMMARIZATION_MODEL=mistral  
      - OLLAMA_MULTILINGUAL_MODEL=llama2
    restart: unless-stopped
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  ollama_data:
    driver: local
  meeting_data:
    driver: local